import Auth from "@/components/Auth";
import firebaseClient from "firebase/client";
import Head from "next/head";
import { useState } from "react";
import { useCollection } from "react-firebase-hooks/firestore";
import Wish from "@/components/Wish";

type Props = {
	currentUser: firebaseClient.User;
};
const Home: React.FC<Props> = ({ currentUser }) => {
	const [wish, setWish] = useState<string>("");
	const [wishes, wishesLoading, wishesError] = useCollection(firebaseClient.firestore().collection("wishes"), {});
	const send = async () => {
		if (wish !== "") {
			await firebaseClient.firestore().collection("wishes").doc(currentUser.uid).set({ wish });
			// kullanıcı sadece 1 tane kayıt ekleyebiliyor uid den dolayı
			// console.log("currentUser: ", currentUser);
			setWish("");
		}
	};
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='mt-2'>
				{!currentUser ? (
					<Auth />
				) : (
					<>
						<h1 className='mb-6 text-white font-semibold text-3xl uppercase'>
							do you have{" "}
							<span className='bg-clip-text text-transparent bg-gradient-to-br from-purple-600 via-pink-500 to-blue-600'>
								something
							</span>
							to say
						</h1>
						<div className='flex space-x-4 mb-6'>
							<input
								type='text'
								className='px-3 py-3 placeholder-grey-900 relative bg-transparent text-white text-sm border-1 border  shadow outline-none focus:outline-none focus:rounded focus:border-purple-900 w-full'
								placeholder='your wish...'
								value={wish}
								onChange={(e) => setWish(e.target.value)}
							/>
							<button
								className='bg-transparent text-white font-semibold hover:text-grey-500 py-2 px-4 border border-purple-500 hover:border-grey-800 rounded'
								onClick={send}>
								Send
							</button>
						</div>
						{wishes?.docs.map((doc) => {
							return (
								// <div key={doc.id} className='flex flex-row justify-between items-center'>
								// 	<span>{`${doc.data().displayName}`}</span>
								// 	<small>{`${doc.data().wish}`}</small>
								// </div>
								<Wish key={doc.id} wish={doc.data().wish} userId={doc.id} />
							);
						})}
					</>
				)}
			</main>
		</div>
	);
};

export default Home;
